### ISSUE TITLE
Subir um docker local com o mongodb

### ISSUE THREAD

**Issue by CharlesQueiroz** [CharlesQueiroz/invertor-digital-wallet#1]
Executar a linha abaixo localmente para rodar o Mongo local: 

docker run --name mongo -p 27017:27017 -d percona/percona-server-mongodb

O banco deverá ficar disponível na porta 27017. Testar pelo IntelliJ: 

<img width="597" alt="Screen Shot 2021-04-05 at 17 12 05" src="https://user-images.githubusercontent.com/2192264/113621492-0e74d100-9632-11eb-884f-e3188352b171.png">

Na aba Databases, clicar no link + e depois escolher mongodb. 

<img width="1109" alt="Screen Shot 2021-04-05 at 17 13 41" src="https://user-images.githubusercontent.com/2192264/113621662-47ad4100-9632-11eb-9e6a-dc9b32519960.png">

Preencher conforme o print e clicar em Test Connection.

**Comment by Renato-Queiroz** [comment]
Realizado e testado conforme solicitado com sucesso.
