### ISSUE TITLE
Salvar ATIVOS no banco de dados 

### ISSUE THREAD

**Issue by CharlesQueiroz** [CharlesQueiroz/invertor-digital-wallet#2]
Implementar a API Rest que, ao receber uma requisição POST, deverá salvar o ATIVO no banco de dados. 

Request: 
----------------------
POST /api/actives 

JSON: 

`
{
    ticket: String,
    description: String
}
`

Alguns Pontos
----

- [x] - Criar a classe que receberá a requisição, chamada ActiveResource

link da doc: 
https://quarkus.io/guides/resteasy-reactive

- [x] - Implementar a entidade usando o MongoPanache

link da doc: 

https://quarkus.io/guides/mongodb-panache

**Comment by Renato-Queiroz** [comment]
Realizado conforme solicitado, nome da classe alterado de ActiveResource para Active.
